import { Metadata } from "next";
import "./globals.css";
import { Header } from "@/components/Layout/Header";
import { Footer } from "@/components/Layout/Footer";


import localFont from 'next/font/local';

const CeraPro = localFont({
  src: [{
    path: '../fonts/CeraPro-Regular.woff2',
    weight: '400',
    style: 'normal'
  },
  {
    path: '../fonts/CeraPro-Regular.woff2',
    weight: '500',
    style: 'normal'
  },
  {
    path: '../fonts/CeraPro-Bold.woff2',
    weight: '700',
    style: 'bold'
  }],
  display: 'swap',
  variable: '--font-CeraPro',
}
);


export const metadata: Metadata = {
  title: "WolfMedia",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={CeraPro.className}>
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html >
  );
}
